services:
  web:
    build:
      context: apps/web
      args:
        - NEXT_PUBLIC_API_BASE=/api
    ports:
      - "3001:3001"
  server:
    build: apps/server
    ports:
      - "3000:3000"
    env_file:
      - apps/server/.env
  caddy:
    build: apps/caddy
    environment:
      - SERVER_UPSTREAM=server:3000
      - WEB_UPSTREAM=web:3001
    ports:
      - "80:80"
    depends_on:
      - web
      - server
