spring.application.name=server
server.port=3000
datasource.db.username=timeoutuser
datasource.db.password=heslo
datasource.db.url=jdbc:mysql://localhost:3306/timeoutdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
ebean.migration.run=true
